name = "Terrassa"
license = "MIT"
licenselink = "https://github.com/danielkvist/hugo-terrassa-theme/blob/master/LICENSE"
description = "A simple, fast and responsive theme for Hugo with a strong focus on accessibility."
homepage = "https://github.com/danielkvist/hugo-terrassa-theme"
tags = ["blog", "clean", "personal", "company", "google analytics", "contact form","mobile", "modern", "accessibility", "font awesome"]
features = [
  "responsive design",
  "accessibility",
  "social icons",
  "contact form",
  "blog",
]
min_version = "0.41"

[author]
  name = "Danielkvist (Daniel Zaragoza)"
  homepage = "https://dkvist.com"
